version: "3.9"
services:
  consul:
    image: hashicorp/consul:1.17
    command: agent -dev -ui -client=0.0.0.0 -dns-port=8600
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    networks:
      micro:
        aliases: [consul]

  product-catalog:
    image: planet/shop-product:1.0.4
    environment:
      - NODE_ENV=dev
      - PORT=3001
      - CONSUL_HOST=consul
    ports:
      - "3001:3001"
    dns:
      - 127.0.0.1
      - 127.0.0.11
    dns_search: ["service.consul"] # for service name resolution (product-catalog.service.consul)
    depends_on:
      - consul
    networks:
      - micro

  basket-service:   # placeholder for later
    image: planet/shop-basket:1.0.4
    environment:
      - NODE_ENV=dev
      - PORT=3002
      - CONSUL_HOST=consul
    ports:
      - "3002:3002"
    # dns:
    #   - 127.0.0.1
    #   - 127.0.0.11
    # dns_search: ["service.consul"] # for service name resolution (product-catalog.service.consul)
    depends_on:
      - rabbitmq
      - product-catalog
    networks:
      - micro

  inventory-service:
    image: planet/shop-inventory:1.0.4
    environment:
      - NODE_ENV=dev
      - PORT=3003
      - CONSUL_HOST=consul
    ports:
      - "3003:3003"
    dns:
      - 127.0.0.1
      - 127.0.0.11
    dns_search: ["service.consul"]
    depends_on:
      - consul
      - rabbitmq
    networks:
      - micro

  rabbitmq:
    image: rabbitmq:3.12-alpine
    ports: ["5672:5672"]
    networks:
      - micro

networks:
  micro:
    driver: bridge